default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: grepp_dev

test:
  <<: *default
  database: grepp_test

production:
  <<: *default
  database: grepp_prod
  username: root
  password: <%= ENV['MEMBER_API_DATABASE_PASSWORD'] %>